Repository opendatadiscovery/odd-collectors, pull requests merged in 2023-12, with the labels that each got.

#29 config loader with secrets backend
  odd-collector-sdk/odd_collector_sdk/collector.py
  odd-collector-sdk/odd_collector_sdk/domain/collector_config_loader.py
  odd-collector-sdk/odd_collector_sdk/secrets/aws/ssm_parameter_store.py
  odd-collector-sdk/odd_collector_sdk/secrets/base_secrets.py
  odd-collector-sdk/odd_collector_sdk/secrets/secrets_backend_factory.py
  odd-collector-sdk/poetry.lock
  odd-collector-sdk/pyproject.toml
  odd-collector/README.md
  odd-collector/collector_config.yaml
  odd-collector/config_examples/ckan.yaml
  odd-collector/odd_collector/__main__.py
  odd-collector/odd_collector/adapters/ckan/tests/conftest.py
  odd-collector/odd_collector/adapters/ckan/tests/test_adapter.py
  odd-collector/odd_collector/adapters/ckan/tests/test_ckan_client.py
Labels: enhancement, chore

#32 Reduce complexity of secret backend config
  README.md
  odd-collector-sdk/odd_collector_sdk/secrets/aws/ssm_parameter_store.py
  odd-collector/README.md
  odd-collector/collector_config.yaml
  odd-collector/config_examples/ckan.yaml
Labels: bug, chore

#34 Add method for attempting dynamical region fetching for AWSSystemsManagerParameterStoreBackend
  odd-collector-sdk/odd_collector_sdk/secrets/aws/ssm_parameter_store.py
Labels: enhancement

#36 Update secrets backend readme and examples
  README.md
  odd-collector-sdk/odd_collector_sdk/secrets/aws/ssm_parameter_store.py
  odd-collector/collector_config.yaml
  odd-collector/config_examples/ckan.yaml
Labels: chore
