Repository opendatadiscovery/odd-collectors, pull requests merged in 2024-02, with the labels that each got.

#40 Implement Relationships ingestion for PostgreSQL adapter
  odd-collector/odd_collector/adapters/postgresql/adapter.py
  odd-collector/odd_collector/adapters/postgresql/mappers/relationships/__init__.py
  odd-collector/odd_collector/adapters/postgresql/mappers/relationships/cardinality_checker.py
  odd-collector/odd_collector/adapters/postgresql/mappers/relationships/identifying_checker.py
  odd-collector/odd_collector/adapters/postgresql/mappers/relationships/mapper.py
  odd-collector/odd_collector/adapters/postgresql/mappers/relationships/relationship_mapper.py
  odd-collector/odd_collector/adapters/postgresql/mappers/relationships/utils.py
  odd-collector/odd_collector/adapters/postgresql/mappers/tables.py
  odd-collector/odd_collector/adapters/postgresql/models.py
  odd-collector/odd_collector/adapters/postgresql/repository.py
  odd-collector/odd_collector/adapters/postgresql/utils.py
  odd-collector/poetry.lock
  odd-collector/pyproject.toml
Labels: enhancement

#46 feature: update relationships mapper according spec
  odd-collector/odd_collector/adapters/postgresql/mappers/relationships/relationship_mapper.py
  odd-collector/poetry.lock
Labels: enhancement

#43 Update README with new Relationships feature
  README.md
Labels: enhancement, chore

#50 Update README "Collector configuration" paragraph with info about configuration settings fetching priority
  README.md
Labels: enhancement, chore

#52 Add handling for cross schema table relationships
  odd-collector/odd_collector/adapters/postgresql/mappers/relationships/mapper.py
  odd-collector/odd_collector/adapters/postgresql/models.py
  odd-collector/odd_collector/adapters/postgresql/repository.py
Labels: enhancement

#54 Fix cardinality direction
  odd-collector/odd_collector/adapters/postgresql/mappers/relationships/README.md
  odd-collector/odd_collector/adapters/postgresql/mappers/relationships/cardinality_checker.py
  odd-collector/odd_collector/adapters/postgresql/mappers/relationships/mapper.py
  odd-collector/odd_collector/adapters/postgresql/mappers/relationships/relationship_mapper.py
  odd-collector/odd_collector/adapters/postgresql/repository.py
Labels: bug, chore

#45 Implement Relationships ingestion for Snowflake adapter
  odd-collector/odd_collector/adapters/snowflake/adapter.py
  odd-collector/odd_collector/adapters/snowflake/client.py
  odd-collector/odd_collector/adapters/snowflake/domain/__init__.py
  odd-collector/odd_collector/adapters/snowflake/domain/fk_constraint.py
  odd-collector/odd_collector/adapters/snowflake/domain/unique_constraint.py
  odd-collector/odd_collector/adapters/snowflake/mappers/__init__.py
  odd-collector/odd_collector/adapters/snowflake/mappers/column.py
  odd-collector/odd_collector/adapters/snowflake/mappers/database.py
  odd-collector/odd_collector/adapters/snowflake/mappers/entity_type_path_key.py
  odd-collector/odd_collector/adapters/snowflake/mappers/metadata.py
  odd-collector/odd_collector/adapters/snowflake/mappers/pipe.py
  odd-collector/odd_collector/adapters/snowflake/mappers/relationships/README.md
  odd-collector/odd_collector/adapters/snowflake/mappers/relationships/__init__.py
  odd-collector/odd_collector/adapters/snowflake/mappers/relationships/cardinality_checker.py
  odd-collector/odd_collector/adapters/snowflake/mappers/relationships/identifying_checker.py
  odd-collector/odd_collector/adapters/snowflake/mappers/relationships/mapper.py
  odd-collector/odd_collector/adapters/snowflake/mappers/relationships/relationship_mapper.py
  odd-collector/odd_collector/adapters/snowflake/mappers/relationships/utils.py
  odd-collector/odd_collector/adapters/snowflake/mappers/schema.py
  odd-collector/odd_collector/adapters/snowflake/mappers/table.py
  odd-collector/odd_collector/adapters/snowflake/mappers/view.py
  odd-collector/poetry.lock
  odd-collector/pyproject.toml
Labels: enhancement, chore

#48 Update README Relationships paragraph with Snowflake
  README.md
Labels: enhancement, chore
